% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Who's that Pokémon?},
  pdfauthor={Maria Briones; Riccardo Dondi; Sayatan Mandal},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Who's that Pokémon?}
\author{Maria Briones \and Riccardo Dondi \and Sayatan Mandal}
\date{}

\begin{document}
\maketitle

\pandocbounded{\includegraphics[keepaspectratio]{/images/pokemon_head.jpg}}

\section{Our mission: catch them all}\label{our-mission-catch-them-all}

A very common issue to every parent is how to advice their 10-year-old
child when the kid is about to leave on a world-wide trip. There are
many important questions to be adressed before the trip, like ``How many
pokemons there are?'', ``Who is the strongest?'' ``How do I catch them
all?''.

On this document we try to provide some insights on the Pokémon world to
help parents to advice their children on how to catch them all. We will
be using the Pokémon dataset from the
\href{https://github.com/rfordatascience/tidytuesday/tree/main}{tidytuesday
repository}, which contains information about all the pokemons from the
first generation to the seventh generation.

\subsection{Data loading and cleaning}\label{data-loading-and-cleaning}

First we need to get our R enviroment ready and load the data. We will
be using the \texttt{tidytuesdayR} package to load the data, which is a
great resource for finding interesting datasets to work with.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#load pacman library to load all the libraries and install if needed}
\FunctionTok{library}\NormalTok{(pacman)}

\CommentTok{\# Load libraries}
\FunctionTok{p\_load}\NormalTok{(tidyverse, }\CommentTok{\#for data manipulation}
\NormalTok{        ggplot2, }\CommentTok{\#for plotting}
\NormalTok{        tidytuesdayR, }\CommentTok{\#to load the data}
\NormalTok{        forcats, }\CommentTok{\#for factor manipulation}
\NormalTok{        farver, }\CommentTok{\#for color manipulation}
\NormalTok{        knitr, }\CommentTok{\#for appealing tables}
\NormalTok{        kableExtra, }\CommentTok{\#for appealing tables}
\NormalTok{        skimr, }\CommentTok{\#for data exploration}
\NormalTok{        viridisLite, }\CommentTok{\#for color palette}
\NormalTok{        ggthemes }\CommentTok{\#for ggplot themes}
\NormalTok{        )}
\end{Highlighting}
\end{Shaded}

With our environment ready we import the data and do some cleaning. We
will be using the
\href{https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-04-01/readme.md}{Pokémon}
dataset, which contains information about all the pokémon from the first
generation to the seventh generation.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# import data Pokémon from tidytuesdayR}
\NormalTok{pokemon\_df }\OtherTok{\textless{}{-}} \FunctionTok{tt\_load}\NormalTok{(}\DecValTok{2025}\NormalTok{, }\AttributeTok{week =} \DecValTok{13}\NormalTok{)}\SpecialCharTok{$}\NormalTok{pokemon\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ---- Compiling #TidyTuesday Information for
## 2025-04-01 ----
## --- There is 1 file available ---
## 
## 
## -- Downloading files -----------------------
## 
##   1 of 1: "pokemon_df.csv"
\end{verbatim}

Our databse contains information about \texttt{\{r\}\ nrow(pokemon\_df)}
pokemons studied on \texttt{\{r\}\ ncol(pokemon\_df)} variables, both
numerical and categorical.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pokemon\_df }\SpecialCharTok{|\textgreater{}} \FunctionTok{skim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule\noalign{}
\endfirsthead
\endhead
\bottomrule\noalign{}
\endlastfoot
Name & pokemon\_df \\
Number of rows & 949 \\
Number of columns & 22 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
character & 10 \\
numeric & 12 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\end{longtable}

\textbf{Variable type: character}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1944}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1389}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1944}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0556}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0556}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0833}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1250}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1528}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
empty
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
whitespace
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
pokemon & 0 & 1.00 & 3 & 23 & 0 & 949 & 0 \\
type\_1 & 0 & 1.00 & 3 & 8 & 0 & 18 & 0 \\
type\_2 & 439 & 0.54 & 3 & 8 & 0 & 18 & 0 \\
color\_1 & 0 & 1.00 & 7 & 7 & 0 & 18 & 0 \\
color\_2 & 439 & 0.54 & 7 & 7 & 0 & 18 & 0 \\
color\_f & 439 & 0.54 & 7 & 7 & 0 & 155 & 0 \\
egg\_group\_1 & 0 & 1.00 & 3 & 13 & 0 & 15 & 0 \\
egg\_group\_2 & 711 & 0.25 & 3 & 13 & 0 & 12 & 0 \\
url\_icon & 228 & 0.76 & 55 & 55 & 0 & 721 & 0 \\
url\_image & 0 & 1.00 & 83 & 85 & 0 & 949 & 0 \\
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1720}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1075}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1505}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0860}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0860}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0538}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0645}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0645}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0645}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0860}}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0645}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hist
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
id & 0 & 1.00 & 1899.77 & 3507.95 & 1.0 & 238.0 & 475.0 & 712.0 &
10147.0 & ▇▁▁▁▂ \\
species\_id & 0 & 1.00 & 400.13 & 239.95 & 1.0 & 191.0 & 395.0 & 615.0 &
802.0 & ▇▇▇▆▇ \\
height & 0 & 1.00 & 1.23 & 1.27 & 0.1 & 0.5 & 1.0 & 1.5 & 14.5 &
▇▁▁▁▁ \\
weight & 0 & 1.00 & 66.21 & 119.95 & 0.1 & 8.5 & 28.8 & 66.6 & 999.9 &
▇▁▁▁▁ \\
base\_experience & 0 & 1.00 & 150.48 & 76.39 & 36.0 & 68.0 & 157.0 &
184.0 & 608.0 & ▇▇▂▁▁ \\
hp & 0 & 1.00 & 68.95 & 25.93 & 1.0 & 50.0 & 65.0 & 80.0 & 255.0 &
▃▇▁▁▁ \\
attack & 0 & 1.00 & 79.47 & 31.95 & 5.0 & 55.0 & 75.0 & 100.0 & 190.0 &
▂▇▆▂▁ \\
defense & 0 & 1.00 & 74.07 & 30.76 & 5.0 & 50.0 & 70.0 & 90.0 & 230.0 &
▃▇▃▁▁ \\
special\_attack & 0 & 1.00 & 72.81 & 32.63 & 10.0 & 50.0 & 65.0 & 95.0 &
194.0 & ▅▇▅▂▁ \\
special\_defense & 0 & 1.00 & 72.22 & 27.68 & 20.0 & 50.0 & 70.0 & 90.0
& 230.0 & ▇▇▂▁▁ \\
speed & 0 & 1.00 & 69.02 & 29.21 & 5.0 & 45.0 & 65.0 & 90.0 & 180.0 &
▃▇▆▂▁ \\
generation\_id & 147 & 0.85 & 3.69 & 1.93 & 1.0 & 2.0 & 4.0 & 5.0 & 7.0
& ▇▅▃▅▅ \\
\end{longtable}

Not all of these features contain valuable information for our analysis,
so we will be selecting only the ones that we think are relevant:

\begin{itemize}
\tightlist
\item
  id: the id of the pokémon
\item
  pokemon: the name of the pokémon
\item
  type\_1: the primary type of the pokémon
\item
  type\_2: the secondary type of the pokémon (if it has one)
\item
  hp: the health points of the pokémon
\item
  attack: the attack points of the pokémon
\item
  defense: the defense points of the pokémon
\item
  special\_attack: the special attack points of the pokémon
\item
  special\_defense: the special defense points of the pokémon
\item
  speed: the speed points of the pokémon
\item
  generation\_id: the generation on wich the pokémon was introduced
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# drop columns that we don\textquotesingle{}t need and which have many NAs}
\NormalTok{pokemon\_df }\OtherTok{\textless{}{-}}\NormalTok{ pokemon\_df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(height, weight, base\_experience, color\_2, color\_f, egg\_group\_2, species\_id, url\_icon, url\_image))}
\end{Highlighting}
\end{Shaded}

One of the first things we notice is that there are some missing values
(NA) on the generation\_id variable (exactly
\texttt{\{r\}\ pokemon\_df\$generation\_id\ \textbar{}\textgreater{}\ is.na()\ \textbar{}\textgreater{}\ sum()}).
After some research on this subset we were able to determine that these
pokemons are all spetial edition pokemons like Charizard Mega X or
Pikachu Pop Star.

In consequence, we will be dropping these pokemons from our analysis,
since they are not representative of the general pokémon population and
they could mislead our insights.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# drop pokemons with missing generation\_id}
\NormalTok{pokemon\_df }\OtherTok{=}\NormalTok{ pokemon\_df }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(generation\_id))}
\end{Highlighting}
\end{Shaded}

Now we have a clean dataset with \texttt{\{r\}\ nrow(pokemon\_df)}
pokemons and \texttt{\{r\}\ ncol(pokemon\_df)} variables.

As we will be performing some analysis on the types of pokemons it's
important to get familiar with these variables. During this process we
noticed that there are some pokemons that have a secondary type and some
that don't
(\texttt{\{r\}\ pokemon\_df\$type\_2\ \textbar{}\textgreater{}\ is.na()\ \textbar{}\textgreater{}\ sum()}
over \texttt{\{r\}\ pokemon\_df\ \ \textbar{}\textgreater{}\ nrow()}).
For the ones that don't have a secondary type, the value of type\_2 is
NA. We will be replacing these NA values with ``None'' to make our
analysis easier.

\includegraphics[width=0.6\linewidth,height=\textheight,keepaspectratio]{/images/types.png}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#manage NAs in type 2}
\NormalTok{pokemon\_df }\OtherTok{=}\NormalTok{ pokemon\_df }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{pokemon =} \FunctionTok{str\_to\_title}\NormalTok{(pokemon), }\CommentTok{\#gives some format to Pokémon names.}
         \AttributeTok{type\_2 =} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(type\_2), }\StringTok{"none"}\NormalTok{, type\_2) }\SpecialCharTok{|\textgreater{}} \FunctionTok{str\_to\_title}\NormalTok{(),}
         \AttributeTok{type\_1 =} \FunctionTok{str\_to\_title}\NormalTok{(type\_1))}
\end{Highlighting}
\end{Shaded}

\section{Three insights on the Pokémon
world}\label{three-insights-on-the-pokuxe9mon-world}

\subsection{1. Pokémon distribution by
generation}\label{pokuxe9mon-distribution-by-generation}

Now is time to adress some of our questions: How many pokemons there are
in each generation? How powerfull are they? We can get some ideas about
these topics by looking at the distribution of pokemons and their most
important stats. To simplify our analysis we combine attack and special
attack on one single variable and do the same for defense.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# to a better analysis we create to combined variables}
\NormalTok{pokemon\_df }\OtherTok{=}\NormalTok{ pokemon\_df }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{comb\_attack =}\NormalTok{ attack }\SpecialCharTok{+}\NormalTok{ special\_attack,}
         \AttributeTok{comb\_defense =}\NormalTok{ defense }\SpecialCharTok{+}\NormalTok{ special\_defense)}
         
\CommentTok{\#summarise pokemon distribution by generation and main stats}
\NormalTok{interest\_stats }\OtherTok{=}\NormalTok{ pokemon\_df }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{group\_by}\NormalTok{(generation\_id) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
            \AttributeTok{avg\_hp =} \FunctionTok{mean}\NormalTok{(hp, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
            \AttributeTok{avg\_attack =} \FunctionTok{mean}\NormalTok{(comb\_attack, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
            \AttributeTok{avg\_defense =} \FunctionTok{mean}\NormalTok{(comb\_defense, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
            \AttributeTok{avg\_speed =} \FunctionTok{mean}\NormalTok{(speed, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{r>{}r>{}r>{}r>{}r>{}r}
\toprule
Generation & Count & HP & C. Attack & C. Defense & Speed\\
\midrule
1 & \cellcolor[HTML]{23898E}{151} & \textcolor{black}{64.21} & \textcolor{black}{140.05} & \textcolor{black}{134.31} & \textcolor[HTML]{830702}{\textbf{69.07}}\\
2 & \cellcolor{transparent}{100} & \textcolor[HTML]{830702}{\textbf{70.98}} & \textcolor{black}{132.76} & \textcolor{black}{142.03} & \textcolor{black}{61.41}\\
3 & \cellcolor[HTML]{2C718E}{135} & \textcolor{black}{65.67} & \textcolor{black}{140.97} & \textcolor{black}{135.47} & \textcolor{black}{61.61}\\
4 & \cellcolor{transparent}{107} & \textcolor[HTML]{830702}{\textbf{73.10}} & \textcolor[HTML]{830702}{\textbf{153.50}} & \textcolor[HTML]{830702}{\textbf{149.68}} & \textcolor[HTML]{830702}{\textbf{69.48}}\\
5 & \cellcolor[HTML]{21908C}{156} & \textcolor{black}{70.31} & \textcolor[HTML]{C72703}{\textbf{150.28}} & \textcolor{black}{138.57} & \textcolor[HTML]{C72703}{\textbf{66.60}}\\
\addlinespace
6 & \cellcolor{transparent}{72} & \textcolor{black}{68.92} & \textcolor{black}{145.04} & \textcolor[HTML]{830702}{\textbf{149.94}} & \textcolor{black}{65.68}\\
7 & \cellcolor{transparent}{81} & \textcolor[HTML]{C72703}{\textbf{70.69}} & \textcolor[HTML]{830702}{\textbf{156.68}} & \textcolor[HTML]{830702}{\textbf{151.89}} & \textcolor{black}{64.54}\\
\bottomrule
\end{longtable}

From this we can see that the most populated generations are the 1st,
3rd and 5th. Nevertheless, the most powerfull generation considering all
four stats (combined attack, combined defense, hp and speed) is the 4th
generation.

\subsection{2. What can we say about
types}\label{what-can-we-say-about-types}

Pokemons come on a wide variety of types. Are some types more common
than others? These are very important questions as we know that
advantages and weaknesses of types are a key element of the Pokémon
world. For example, water type pokemons are strong against fire type
pokemons but weak against electric type pokemons. In consequence, if we
want to catch them all we need to know which types are more common and
which types are more powerful.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#table for count of pokemon by type and generation }
\NormalTok{pokemon\_df }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{group\_by}\NormalTok{(generation\_id, type\_1) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ generation\_id, }\AttributeTok{values\_from =}\NormalTok{ n, }\AttributeTok{values\_fill =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Total =} \FunctionTok{rowSums}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.numeric)))) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Primary type"}\NormalTok{, }\StringTok{"Gen 1"}\NormalTok{, }\StringTok{"Gen 2"}\NormalTok{, }\StringTok{"Gen 3"}\NormalTok{, }\StringTok{"Gen 4"}\NormalTok{, }\StringTok{"Gen 5"}\NormalTok{, }\StringTok{"Gen 6"}\NormalTok{,}
                      \StringTok{"Gen 7"}\NormalTok{, }\StringTok{"Total"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{, }\StringTok{"responsive"}\NormalTok{),}
                \AttributeTok{full\_width =}\NormalTok{ F, }\AttributeTok{position =} \StringTok{"center"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has regrouped the output.
## i Summaries were computed grouped by
##   generation_id and type_1.
## i Output is grouped by generation_id.
## i Use `summarise(.groups = "drop_last")` to
##   silence this message.
## i Use `summarise(.by = c(generation_id,
##   type_1))` for ]8;;x-r-help:dplyr::dplyr_byper-operation grouping]8;;
##   instead.
\end{verbatim}

\begin{longtable}[t]{lrrrrrrrr}
\toprule
Primary type & Gen 1 & Gen 2 & Gen 3 & Gen 4 & Gen 5 & Gen 6 & Gen 7 & Total\\
\midrule
Bug & 12 & 10 & 12 & 8 & 18 & 3 & 9 & 72\\
Dragon & 3 & 0 & 7 & 3 & 7 & 4 & 3 & 27\\
Electric & 9 & 6 & 4 & 7 & 7 & 3 & 3 & 39\\
Fairy & 2 & 5 & 0 & 1 & 0 & 9 & 1 & 18\\
Fighting & 7 & 2 & 4 & 2 & 7 & 3 & 4 & 29\\
\addlinespace
Fire & 12 & 8 & 6 & 5 & 8 & 8 & 5 & 52\\
Ghost & 3 & 1 & 4 & 6 & 5 & 4 & 4 & 27\\
Grass & 12 & 9 & 12 & 13 & 15 & 5 & 12 & 78\\
Ground & 8 & 3 & 6 & 4 & 9 & 0 & 2 & 32\\
Ice & 2 & 4 & 6 & 3 & 6 & 2 & 0 & 23\\
\addlinespace
Normal & 22 & 15 & 18 & 17 & 17 & 4 & 12 & 105\\
Poison & 14 & 1 & 3 & 6 & 2 & 2 & 4 & 32\\
Psychic & 8 & 7 & 8 & 7 & 14 & 3 & 6 & 53\\
Rock & 9 & 4 & 8 & 6 & 6 & 8 & 4 & 45\\
Water & 28 & 18 & 24 & 13 & 17 & 5 & 9 & 114\\
\addlinespace
Dark & 0 & 5 & 4 & 3 & 13 & 3 & 1 & 29\\
Steel & 0 & 2 & 9 & 3 & 4 & 4 & 2 & 24\\
Flying & 0 & 0 & 0 & 0 & 1 & 2 & 0 & 3\\
\bottomrule
\end{longtable}

We can see that the most common types are water, normal and Grass.
However, these types are not equally distributed across generations. For
example, the water type is more common in the 1st generation than in the
4th generation and Normal type is the rarest main type on the 6th
generation.

\subsection{3. Dual-type vs Single-type}\label{dual-type-vs-single-type}

With this said. Do Dual-type Pokémon (those with a secondary type)
consistently outperform single-types in raw power? As they may be less
common they might be worth the effort of chasing them. We engineer
\texttt{is\_dual\_type} to identify this pokemons and then explore and
quantify the gap.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ pokemon\_df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{type\_2       =} \FunctionTok{na\_if}\NormalTok{(type\_2, }\StringTok{"None"}\NormalTok{),}
    \AttributeTok{is\_dual\_type =} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(type\_2),}
    \AttributeTok{power\_stats  =}\NormalTok{ hp }\SpecialCharTok{+}\NormalTok{ attack }\SpecialCharTok{+}\NormalTok{ defense }\SpecialCharTok{+}\NormalTok{ special\_attack }\SpecialCharTok{+}\NormalTok{ special\_defense }\SpecialCharTok{+}\NormalTok{ speed}
\NormalTok{  )}

\NormalTok{dual\_summary }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(is\_dual\_type) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n            =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_power   =} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(power\_stats), }\DecValTok{1}\NormalTok{),}
    \AttributeTok{median\_power =} \FunctionTok{round}\NormalTok{(}\FunctionTok{median}\NormalTok{(power\_stats), }\DecValTok{1}\NormalTok{),}
    \AttributeTok{sd\_power     =} \FunctionTok{round}\NormalTok{(}\FunctionTok{sd}\NormalTok{(power\_stats), }\DecValTok{1}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\NormalTok{dual\_summary }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"is Dual?"}\NormalTok{, }\StringTok{"Count"}\NormalTok{, }\StringTok{"Mean Power"}\NormalTok{, }\StringTok{"Median Power"}\NormalTok{, }\StringTok{"Power SD"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
                \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrr}
\toprule
is Dual? & Count & Mean Power & Median Power & Power SD\\
\midrule
FALSE & 400 & 403.8 & 405 & 109.8\\
TRUE & 402 & 438.4 & 460 & 109.3\\
\bottomrule
\end{longtable}

As we can see, Dual-type Pokémon average \textbf{438.4} total stats vs
\textbf{403.8} for single-types --- a \textasciitilde35-point (8.56\%)
gap.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{type\_dual }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(type\_1, is\_dual\_type) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n          =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_power =} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(power\_stats), }\DecValTok{1}\NormalTok{),}
    \AttributeTok{.groups    =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(n }\SpecialCharTok{\textgreater{}=} \DecValTok{5}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(mean\_power))}

\NormalTok{type\_dual }\SpecialCharTok{|\textgreater{}} \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{10}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Primary Type"}\NormalTok{, }\StringTok{"is Dual?"}\NormalTok{, }\StringTok{"Count"}\NormalTok{, }\StringTok{"Mean Power"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
                \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{llrr}
\toprule
Primary Type & is Dual? & Count & Mean Power\\
\midrule
Dragon & TRUE & 15 & 568.0\\
Fire & TRUE & 22 & 490.5\\
Psychic & TRUE & 18 & 484.4\\
Steel & TRUE & 20 & 477.9\\
Fighting & TRUE & 7 & 469.7\\
\addlinespace
Electric & TRUE & 12 & 463.2\\
Rock & TRUE & 34 & 450.4\\
Dark & TRUE & 20 & 447.3\\
Ground & TRUE & 17 & 440.7\\
Ice & FALSE & 12 & 438.6\\
\bottomrule
\end{longtable}

Dragon dual-types lead all groups at 568 power average. Fire types
follows far behind with and average of 490.5 on power stats.

\pandocbounded{\includegraphics[keepaspectratio]{/images/strong_c.gif}}

\section{Visualizations}\label{visualizations}

\subsection{1. Type proportion on our
sample}\label{type-proportion-on-our-sample}

The analysis from table @tbl-type\_distribution can be enriched if we
consider the secondary type of pokemons. Considerin the 18 main types
and the 19 secondary types (including ``None'') there are 342 possible
combinations we can create a heatmap to visualize the proportion of
pokemons by type 1 and type 2 across the total universe of registered
pokemons. This will allow us to see which combinations of types are more
common and which are more rare.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# count of pokemon by type 1 and type 2}
\NormalTok{poke\_type }\OtherTok{\textless{}{-}}\NormalTok{ pokemon\_df}\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{group\_by}\NormalTok{(type\_1, type\_2) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{complete}\NormalTok{(type\_1, type\_2, }\AttributeTok{fill =} \FunctionTok{list}\NormalTok{(}\AttributeTok{n =} \DecValTok{0}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{ungroup}\NormalTok{() }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prop =}\NormalTok{ n }\SpecialCharTok{*} \DecValTok{100} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n), }
         \AttributeTok{norm\_prop =} \FunctionTok{case\_when}\NormalTok{ (prop}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\textasciitilde{}} \SpecialCharTok{{-}}\FloatTok{2.1}\NormalTok{,}
                                \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \FunctionTok{log}\NormalTok{(prop))}
\NormalTok{        )}

\NormalTok{poke\_type }\OtherTok{\textless{}{-}}\NormalTok{ poke\_type }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{type\_2 =} \FunctionTok{fct\_relevel}\NormalTok{(type\_2, }\StringTok{"None"}\NormalTok{)) }\CommentTok{\#we make it a factor so "None" appears first}

\CommentTok{\#graph }
\FunctionTok{ggplot}\NormalTok{(poke\_type, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ type\_2, }\AttributeTok{y =}\NormalTok{ type\_1, }\AttributeTok{fill =}\NormalTok{ norm\_prop)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"lightgrey"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient}\NormalTok{(}\AttributeTok{low =} \StringTok{"white"}\NormalTok{, }\AttributeTok{high =} \StringTok{"\#B22222"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Normalized proportion of pokemons by types"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Secondary Type"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Main Type"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Norm. Prop."}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Normalization is performed as ln(proportion) to better visualize types with low proportions."}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/type-heatmap-1.pdf}}
\caption{Normalized proportion of pokemons by types}
\end{figure}

Assuming that each pokémon species distributed homogeneously across the
world, meaning that for example catching a Blastoise is as likely as
catching a Squirtle (strong assumption), we could say that the most
abuntant pokemons belong to the Water-None combination.

Outside the None secondary type, the most common combinations are
Normal-Flying (like Pidgey), Grass-Poison (like Bulbasaur) and
Bug-Flying (like Butterfree). On the other hand, there are 42
combinations that have only one pokémon species, like the Ghost-Fairy,
Fire-Dark, or Dragon-Electric.

\subsection{2. Distribution of stats by
type}\label{distribution-of-stats-by-type}

We had done a visualization on the distribituion of stats w.r.t the
generation but we did not see any changes that made sense as the
generation increased.

So we try to see the different stats of different types of pokemons and
we can look at the graph and find out the Strongest , Weakest , Slowest
or Fastest types of pokemons.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#new interest stats by type}
\CommentTok{\# 1. Aggregate data by Type only}
\NormalTok{type\_summary }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(type\_1) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \CommentTok{\# Calculate the means of the sums directly}
    \AttributeTok{attack\_total  =} \FunctionTok{mean}\NormalTok{(attack }\SpecialCharTok{+}\NormalTok{ special\_attack, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{defense\_total =} \FunctionTok{mean}\NormalTok{(defense }\SpecialCharTok{+}\NormalTok{ special\_defense, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{speed         =} \FunctionTok{mean}\NormalTok{(speed, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{hp            =} \FunctionTok{mean}\NormalTok{(hp, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(attack\_total)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{type\_1 =} \FunctionTok{factor}\NormalTok{(type\_1, }\AttributeTok{levels =}\NormalTok{ type\_1))}

\CommentTok{\# 2. Pivot (Note: Ensure the names match your new columns)}
\NormalTok{type\_long }\OtherTok{\textless{}{-}}\NormalTok{ type\_summary }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_longer}\NormalTok{(}
    \AttributeTok{cols =} \FunctionTok{c}\NormalTok{(attack\_total, defense\_total),}
    \AttributeTok{names\_to =} \StringTok{"stat\_name"}\NormalTok{,}
    \AttributeTok{values\_to =} \StringTok{"stat\_value"}
\NormalTok{  )}

\CommentTok{\# 3. Plot}
\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}
    \AttributeTok{data =}\NormalTok{ type\_long,}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ type\_1, }\AttributeTok{y =}\NormalTok{ stat\_value, }\AttributeTok{fill =}\NormalTok{ stat\_name),}
    \AttributeTok{position =} \FunctionTok{position\_dodge}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.7}\NormalTok{), }\AttributeTok{alpha =} \FloatTok{0.8}
\NormalTok{  ) }\SpecialCharTok{+}
  \CommentTok{\# Dashed line for Speed}
  \FunctionTok{geom\_line}\NormalTok{(}
    \AttributeTok{data =}\NormalTok{ type\_summary,}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ type\_1, }\AttributeTok{y =}\NormalTok{ speed, }\AttributeTok{group =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"Avg Speed"}\NormalTok{),}
    \AttributeTok{linewidth =} \FloatTok{1.2}
\NormalTok{  ) }\SpecialCharTok{+}
  \CommentTok{\# Solid line for HP}
  \FunctionTok{geom\_line}\NormalTok{(}
    \AttributeTok{data =}\NormalTok{ type\_summary,}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ type\_1, }\AttributeTok{y =}\NormalTok{ hp, }\AttributeTok{group =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"Avg HP"}\NormalTok{),}
    \AttributeTok{linewidth =} \FloatTok{1.2}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{data =}\NormalTok{ type\_summary, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ type\_1, }\AttributeTok{y =}\NormalTok{ speed, }\AttributeTok{color =} \StringTok{"Avg Speed"}\NormalTok{), }\AttributeTok{size =} \DecValTok{3}\NormalTok{, }\AttributeTok{shape =} \DecValTok{16}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{data =}\NormalTok{ type\_summary, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ type\_1, }\AttributeTok{y =}\NormalTok{ hp, }\AttributeTok{color =} \StringTok{"Avg HP"}\NormalTok{), }\AttributeTok{size =} \DecValTok{3}\NormalTok{, }\AttributeTok{shape =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}
    \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"attack\_total"} \OtherTok{=} \StringTok{"\#EF5350"}\NormalTok{, }\StringTok{"defense\_total"} \OtherTok{=} \StringTok{"\#42A5F5"}\NormalTok{), }\CommentTok{\# Updated names}
    \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Total Attack"}\NormalTok{, }\StringTok{"Total Defense"}\NormalTok{), }
    \AttributeTok{name =} \StringTok{"Base Stats"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}
    \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Avg Speed"} \OtherTok{=} \StringTok{"\#FFA800"}\NormalTok{, }\StringTok{"Avg HP"} \OtherTok{=} \StringTok{"\#059142"}\NormalTok{),}
    \AttributeTok{name =} \StringTok{"Trends"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_clean}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Average Stats by Primary Type"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Primary Type"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Average Value"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/fig_type-stats-1.pdf}}
\caption{Average Stats by Primary Type}
\end{figure}

\subsection{3. Single vs Dual-type stat
distributions}\label{single-vs-dual-type-stat-distributions}

Coming back to the Dual-type analysis, we perform a violin chart to
visualize the distribution of our summarising power stat across the
different primary type categories.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Order types by median total stats (dual{-}type)}
\NormalTok{type\_order }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(is\_dual\_type) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(type\_1) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{med =} \FunctionTok{median}\NormalTok{(power\_stats), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(med)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{pull}\NormalTok{(type\_1)}

\NormalTok{df }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{type\_1       =} \FunctionTok{factor}\NormalTok{(type\_1, }\AttributeTok{levels =}\NormalTok{ type\_order),}
    \AttributeTok{typing\_label =} \FunctionTok{if\_else}\NormalTok{(is\_dual\_type, }\StringTok{"Dual{-}type"}\NormalTok{, }\StringTok{"Single{-}type"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ type\_1, }\AttributeTok{y =}\NormalTok{ power\_stats, }\AttributeTok{fill =}\NormalTok{ typing\_label)) }\SpecialCharTok{+}
  \FunctionTok{geom\_violin}\NormalTok{(}
    \AttributeTok{position =} \FunctionTok{position\_dodge}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.85}\NormalTok{),}
    \AttributeTok{alpha =} \FloatTok{0.65}\NormalTok{, }\AttributeTok{colour =} \ConstantTok{NA}\NormalTok{, }\AttributeTok{scale =} \StringTok{"width"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{group =}\NormalTok{ typing\_label),}
    \AttributeTok{fun =}\NormalTok{ median, }\AttributeTok{geom =} \StringTok{"point"}\NormalTok{, }\AttributeTok{shape =} \DecValTok{21}\NormalTok{,}
    \AttributeTok{colour =} \StringTok{"white"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"white"}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.5}\NormalTok{,}
    \AttributeTok{position =} \FunctionTok{position\_dodge}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.85}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}
    \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Single{-}type"} \OtherTok{=} \StringTok{"\#4FC3F7"}\NormalTok{, }\StringTok{"Dual{-}type"} \OtherTok{=} \StringTok{"\#FF6B35"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{800}\NormalTok{, }\DecValTok{100}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title    =} \StringTok{"Power Base Stats by Primary Type — Single vs Dual{-}typing"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Types ordered by dual{-}type median. White dots = median."}\NormalTok{,}
    \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Total Base Stats"}\NormalTok{, }\AttributeTok{fill =} \ConstantTok{NULL}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{11}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{plot.background  =} \FunctionTok{element\_rect}\NormalTok{(}\AttributeTok{fill =} \StringTok{"\#0D0D1A"}\NormalTok{, }\AttributeTok{colour =} \ConstantTok{NA}\NormalTok{),}
    \AttributeTok{panel.background =} \FunctionTok{element\_rect}\NormalTok{(}\AttributeTok{fill =} \StringTok{"\#0D0D1A"}\NormalTok{, }\AttributeTok{colour =} \ConstantTok{NA}\NormalTok{),}
    \AttributeTok{panel.grid.major.y =} \FunctionTok{element\_line}\NormalTok{(}\AttributeTok{colour =} \StringTok{"\#1E1E3A"}\NormalTok{),}
    \AttributeTok{panel.grid.major.x =} \FunctionTok{element\_blank}\NormalTok{(),}
    \AttributeTok{panel.grid.minor   =} \FunctionTok{element\_blank}\NormalTok{(),}
    \AttributeTok{axis.text   =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{colour =} \StringTok{"\#9E9EA0"}\NormalTok{),}
    \AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{35}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{face =} \StringTok{"bold"}\NormalTok{),}
    \AttributeTok{axis.title  =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{colour =} \StringTok{"\#C0C0D0"}\NormalTok{),}
    \AttributeTok{plot.title    =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{colour =} \StringTok{"white"}\NormalTok{, }\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{14}\NormalTok{),}
    \AttributeTok{plot.subtitle =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{colour =} \StringTok{"\#7B7B9E"}\NormalTok{, }\AttributeTok{size =} \DecValTok{10}\NormalTok{),}
    \AttributeTok{legend.background =} \FunctionTok{element\_rect}\NormalTok{(}\AttributeTok{fill =} \StringTok{"\#13132A"}\NormalTok{, }\AttributeTok{colour =} \ConstantTok{NA}\NormalTok{),}
    \AttributeTok{legend.text  =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{colour =} \StringTok{"white"}\NormalTok{),}
    \AttributeTok{legend.position =} \StringTok{"top"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Groups with fewer than two datapoints have
## been dropped.
## i Set `drop = FALSE` to consider such
##   groups for position adjustment purposes.
\end{verbatim}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/ggplot-viz-1-1.pdf}}
\caption{Power Base Stats by Primary Type --- Single vs Dual-typing}
\end{figure}

Nearly every primary type shows the orange (dual-type) violin sitting
higher than the blue (single-type) one. Dragon dual-types are especially
concentrated at the top as we saw on @tbl-dualtype\_stats; Normal
single-types show the widest spread due to a large pool of filler
Pokémon.

\section{Then who's our pokemon?}\label{then-whos-our-pokemon}

Considering our analysis, the most competitive Pokémon is
\textbf{Garchomp}: a Dragon-Ground dual-type from the 4th generation
with a stat power of 608 points, 130 attack and 95 defense.

\includegraphics[width=3.03125in,height=\textheight,keepaspectratio]{/images/garchomp.png}

\emph{Authors note}: After all of this our analysis, we are still
betting on Pikachu. ⚡

\section{Conclusion}\label{conclusion}

After exploring the Pokémon universe across types, generations, and stat
distributions, we can finally offer some battle-tested advice to any
10-year-old setting out on their journey.

\textbf{Generation matters --- but not in the way you might expect.}
While generations 1, 3, and 5 offer the largest variety of species to
catch, it is generation 4 that consistently produces the most powerful
Pokémon across all key stats (HP, attack, defense, and speed). A detour
through the Sinnoh region is well worth it.

\textbf{Dual-type Pokémon are worth the extra effort.} Prioritise
dual-type Pokémon, pay attention to generation 4, and do not
underestimate type synergy.

\end{document}
